-- Revoke privileges from core user
REVOKE ALL PRIVILEGES ON DATABASE crm FROM core;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM core;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM core;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM core;

-- Drop core user
DROP USER IF EXISTS core; 